#!/bin/bash 
es_home=/opt/module/elasticsearch
kibana_home=/opt/module/kibana
hadoop_home=/opt/module/hadoop-3.1.3
kafka_home=/opt/module/kafka
case $1  in
 "start") {
  echo "bn" | sudo -S sh -c "systemctl start mysqld 2>&1 &"
  ${hadoop_home}/sbin/start-dfs.sh 2>&1 &
  ssh hadoop103 "${hadoop_home}/sbin/start-yarn.sh 2>&1 &"
  for i in hadoop102 hadoop103 hadoop104
  do
    ssh $i "zkServer.sh start 2>&1 &"
  done
  sleep 10s
  hiveservices.sh start 2>&1 &
  for i in hadoop102 hadoop103 hadoop104
  do
    ssh $i "kafka-server-start.sh -daemon ${kafka_home}/config/server.properties 2>&1 &"
    ssh $i  "source /etc/profile;${es_home}/bin/elasticsearch >/dev/null 2>&1 &"
  done
  nohup ${kibana_home}/bin/kibana >/home/lsj/kibana.log 2>&1 &
 
};;
"stop") {
  ps -ef|grep ${kibana_home} |grep -v grep|awk '{print $2}'|xargs kill
  for i in hadoop102 hadoop103 hadoop104
  do
      ssh $i "ps -ef|grep $es_home |grep -v grep|awk '{print \$2}'|xargs kill" >/dev/null 2>&1
      ssh $i "kafka-server-stop.sh 2>&1"
  done
  sleep 10s
  for i in hadoop102 hadoop103 hadoop104
  do
      ssh $i "zkServer.sh stop 2>&1"
  done

  hiveservices.sh stop 2>&1 &
  echo "bn" | sudo -S sh -c "systemctl stop mysqld 2>&1 &"
  ssh hadoop103 "${hadoop_home}/sbin/stop-yarn.sh 2>&1 &"
  ${hadoop_home}/sbin/stop-dfs.sh 2>&1 &
};;
esac
